### ISSUE TITLE
DataRecognition/Visualization: many error messages of form "Glyph 30452 missing from current font."

### ISSUE THREAD

**Issue by patfla** [MemoryForSky/MLTools#1]
I've succeeded in switching my browser over to Chinese

https://imgur.com/a/Vwyy7kq

but am still getting errors of form "Glyph 30452 missing from current font." where glyph 30452 I assume (Caucasian American but speak and read Japanese) refers to a specific character.

**Comment by MemoryForSky** [comment]
The warning should not influence the result.
if you want to slove this warning, i think you can add this code in test_visual_tool.ipynb.
```
plt.rcParams['font.sans-serif'] = ['SimHei']
plt.rcParams['axes.unicode_minus'] = False
```

**Comment by patfla** [comment]
Thanks.  However, while it no longer throws the errors I saw before, the labels aren't rendering:

https://imgur.com/a/YHgzYf9

influence the result>  actually, I'm not just interested in the numbers and analysis but I'd like to be able to read the text as well.

**Comment by patfla** [comment]
I find that when I switch to SimSun

`plt.rcParams['font.sans-serif'] = ['SimSun']`

the labels do render properly

https://imgur.com/a/jaRHv5x

so I think I'm good for the time being.

**Comment by patfla** [comment]
I believe SimSun is not sans-serif - SimSun is serif to SimHei's sans-serif.  But the fix works well enough for present needs.

**Comment by MemoryForSky** [comment]
That's good.
